### PR TITLE
Compress packet

### PR DESCRIPTION
**Pull request by Kvel2D**

### CODE REVIEW

**Review by JiahuiDai — COMMENTED** [review]
what does the 65536.0f do in compress_float()

**Comment by JingyaGao** [comment]
from my understanding, the compression function is limiting the range of reading to 0-40f and turning it into a uint16_t by multiplying the ratio (reading : 40f) and 65536 (max for uint16_t). So the data transmitted will be a percentage representation of the actual reading. Is this correct?

**Comment by Kvel2D** [comment]
Changed 65536 to UINT16_MAX.
Yes, it's subdividing 0.0-40.0 float range into 65536 floats.

**Comment by Kvel2D** [comment]
> If f = 100.0f, a reading will have chance to be 5 char (it should be 4 char only) in print_packet.

Good catch, forgot about that.

**Pull request merged**
